#!/bin/env bash

cat <<EOF
-=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=-
 BY URIID1
 Source https://github.com/uriid1/bash-tools
-=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=-
EOF

readonly BIN_PATH="${HOME}/.local/bin/uriid1/bin"

readonly EXIT_SUCCESS=0
readonly EXIT_FAILURE=1

log() {
  echo -e "\033[1;32m-->\033[0m $1"
}

warn() {
  echo -e "\033[1;33m[!]\033[0m $1"
}

#
# Checking that base tools installed 
#

base_tools=(adb dig iptables wc sysctl wget python bc readlink lsblk column jq)

for ((i = 0; i < ${#base_tools[*]}; ++i)); do
  tool="${base_tools[$i]}"

  if ! [ "$(which -a $tool . 2>/dev/null)" ]; then
    warn "Not found: ${tool}"
  fi
done

#
# Check path
#

if ! echo "${PATH}" | grep -q "${BIN_PATH}"; then
  warn "By default, scripts are placed in the directory ${BIN_PATH}"
  warn "But in your \$PATH variable set in env, this path is not included."
  warn "Set it manually, for example, if you are using bash -"
  warn "add the line \`export PATH=\"\$PATH:${BIN_PATH}\"\` to ~/.bashrc"
  exit $EXIT_FAILURE
fi

#
# Installing
#

chmod +x bin/*
mkdir -p "${BIN_PATH}"

for script in bin/*; do
  name=$(basename $script)

  log "Copy ${name} to ${BIN_PATH}"
  cp $script ${BIN_PATH}
done
