#!/bin/env bash

cat <<EOF
-=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=-
 BY URIID1
 Source https://github.com/uriid1/bash-tools
-=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=-
EOF

readonly EXIT_SUCCESS=0
readonly EXIT_FAILURE=1

readonly TOOLS_PATH="${HOME}/.local/bin/uriid1"

log() {
  echo -e "\033[1;32m-->\033[0m $1"
}

rm -rf ${TOOLS_PATH}

log "Done!"
