#!/usr/bin/env bash
set -euo pipefail

readonly EXIT_SUCCESS=0
readonly EXIT_FAILURE=1
readonly _VERSION='1.0'

function help() {
  local sname=$(echo "$0" | sed 's/.*\///')

cat <<EOF
By: uriid1
  Version: $_VERSION

Usage:
  $sname --process <binary> [--start|--stop|--status|--restart]

Options:
  --start       Start process
  --stop        Stop process
  --status      Show process status
  --restart     Restart process
  --process     Path to binary or command name

Example:
  $sname --process "./mybinfile" --start
EOF
}

process_name=
process_pid=
process_log=
setvars() {
  local name="$1"
  process_name="$name"
  process_log="${process_name}.log"
  process_pid="${process_name}.pid"
}

start() {
  if [[ -f "$process_pid" ]]; then
    local pid
    pid=$(<"$process_pid")

    if ps -p "$pid" > /dev/null 2>&1; then
      echo "${process_name} already running (PID: $pid)"
      exit $EXIT_SUCCESS
    else
      echo "Remove old pid file..."
      rm -f "$process_pid"
    fi
  fi

  echo "$process_name stated..."
  nohup "$process_name" >>"$process_log" 2>&1 < /dev/null &
  echo $! > "$process_pid"

  echo "PID: $(<"$process_pid")"
  echo "LOG: $process_log"
}

stop() {
  if [[ ! -f "$process_pid" ]]; then
    echo "${process_name} not running (PID file non exists)"
    exit $EXIT_SUCCESS
  fi

  local pid=$(<"$process_pid")

  if ps -p "$pid" > /dev/null 2>&1; then
    echo "${process_name} stopping (PID: $pid)..."

    kill "$pid"
    sleep 1
    if ps -p "$pid" > /dev/null 2>&1; then
      echo "Force stop..."
      kill -9 "$pid"
    fi
  else
    echo "${process_name} process not found | Remove pid-file"
  fi

  rm -f "$process_pid"
  echo "${process_name} stopped"
}

status() {
  if [[ -f "$process_pid" ]]; then
    local pid=$(<"$process_pid")

    if ps -p "$pid" > /dev/null 2>&1; then
      echo "${process_name} is working (PID: $pid)"
      exit $EXIT_SUCCESS
    else
      echo "PID-file not found, but process not active"
      exit $EXIT_FAILURE
    fi
  else
    echo "${process_name} not running..."
    exit $EXIT_FAILURE
  fi
}

case "$1" in
  --help | -h)
    help
    exit $EXIT_SUCCESS
  ;;
esac

while [[ $# -gt 0 ]]; do
  case "$1" in
    --help | -h)
      help
      exit $EXIT_SUCCESS
    ;;
    --process)
      setvars "$2"
      shift 2
    ;;
    --start)
      start
      shift 1
    ;;
    --stop)
      stop
      shift 1
    ;;
    --status)
      status
      shift 1
    ;;
    --restart)
      stop
      start
      shift 1
    ;;
    *)
      echo "Unknown option: $1"
      exit $EXIT_FAILURE
      ;;
  esac
done

if [[ -z "${process_name:-}" ]]; then
  echo "Error: --process argument is required"
  exit $EXIT_FAILURE
fi
